const DISPLAY_NAMES: Record<string, string> = {
  weather: '天气查询',
  get_current_weather: '天气查询',
  holiday_calendar: '节假日查询',
  tavily_search: 'Tavily 搜索',
  tavily_extract: 'Tavily 提取',
  holiday: '节假日查询',
  image_understand: '图片理解',
  analyze_image: '图片理解',
  map_nearby: '周边搜索',
  map_geocode: '地理编码',
  map_transit: '公交换乘',
  map_cycling: '骑行路线',
  map_fuzzy_addr: '地址解析',
  file_read: '读取文件',
  file_write: '写入文件',
  file_list: '文件列表',
  file_operations: '文件操作',
  pdf_reader: 'PDF 阅读',
  doc_reader: '文档阅读',
  syntax_check: '语法检查',
  syntax_checker: '语法检查',
  code_quality: '代码质量',
  code_quality_analyzer: '代码质量',
  unit_test: '单元测试',
  unit_test_runner: '单元测试',
  debug: '调试',
  debugger: '调试',
  todo_add: '添加待办',
  todo_list: '待办列表',
  todo_complete: '完成待办',
  todo_uncomplete: '取消完成',
  todo_delete: '删除待办',
  todo_update: '更新待办',
  todo_query: '查询待办',
  todo_list_projects: '项目列表',
  todo_add_quick: '快速添加待办',
  todo_list_sections: '分区列表',
  todo_list_labels: '标签列表',
  time: '时间查询',
  time_tool: '时间查询',
  python: 'Python 执行',
  run_python: 'Python 执行',
  nearby_search: '周边搜索',
  fuzzy_address_search: '模糊地址搜索',
  geocode_address: '地理编码',
  get_transit_route: '公交换乘',
  get_cycling_route: '骑行路线',
  tarot: '塔罗牌',
  answer_book: '答案之书',
  ask_user: '询问用户',
  ask_user_for_info: '询问用户',
  ask_user_qa: '询问用户',
  ask_user_single_choice: '请选择',
  ask_user_multi_choice: '多选',
  task_tracker: '任务追踪',

  /* Memory */
  list_memories: '记忆列表',
  read_memories: '读取记忆',
  create_memory: '创建记忆',
  update_memory: '更新记忆',
  delete_memory: '删除记忆',
  merge_memories: '合并记忆',
}
export function toolDisplayName(name: string): string {
  if (DISPLAY_NAMES[name]) return DISPLAY_NAMES[name]
  return name
}

/** 所有已知工具名称列表（供 Playground 使用） */
export const ALL_TOOL_NAMES = Object.keys(DISPLAY_NAMES)
